### ISSUE TITLE
Grant access to restricted records by CERN users/e-groups

### ISSUE THREAD

**Issue by jbenito3** [CERNDocumentServer/cds-rdm#109]
Record owners should be able to choose with whom to share (person or e-group) and type of access (edit/view)
- check what issues are already open in `inveniosoftware`
- the person tab should be visible/enable for all InvenioRDM instances
- the group tab should be controlled by the feature flag
- see mockups already ready
- create a list of tasks

### Landing page
- Integrated in the current black Share button, and reusing the first tab of it (persons).
- Explore and demo changing the "create new link" button/row of the `Links` tab above the list, as in the bottom is counterintuitive

### Upload form
- The Share button should also be in the draft/edit page.
- We should be able to share a draft for preview and for edition.

TASKS TO DO:

- [x] not be able to add multiple users with different permissions
- [x] https://github.com/inveniosoftware/invenio-rdm-records/issues/1671
- [x] [add access/[groups|users|grants] to allow to delete based on user/group id as well](https://github.com/inveniosoftware/invenio-rdm-records/issues/1672)
- [x] https://github.com/inveniosoftware/invenio-app-rdm/issues/2436
- [x] https://github.com/inveniosoftware/invenio-app-rdm/issues/2592
- [x] https://github.com/inveniosoftware/invenio-app-rdm/issues/2593
- [x] Remove the extra fetching groups and links
- [x] [Share the draft](https://github.com/inveniosoftware/invenio-app-rdm/issues/2667)
- [ ] [Rework the row to add a new link in the Links tab, to be similar to the other tabs](https://github.com/CERNDocumentServer/cds-rdm/issues/161)
- [ ] #114
- [ ] [nice to have: show who has access in a readable way, and why](https://github.com/CERNDocumentServer/cds-rdm/issues/162)
