### ISSUE TITLE
CERN Person ID and creators identifiers

### ISSUE THREAD

**Issue by kpsherva** [CERNDocumentServer/cds-rdm#281]
After several discussions, we did not come up with a simple and acceptable solution to keep the CERN Person ID restricted, and add it to each record in the creators/contributors field.

The main challenge is related to how the creators identifiers are added to the record: such identifiers are copied by the UI over to the record when saving/publishing, potentially disclosing the Person ID of all CERN users to the uploader on the UI.
We could have found solutions if the backend was taking care of copying the creator info to the record. This would have allowed keeping the Person ID restricted and accessible only to some users (tokens). However, it would also have required adding the primary key of the names vocabulary (which might not be stable) to the record, so that existing records can be editing, without losing the previously added Person ID.

The Person ID is important when exchanging data with other systems at CERN (e.g. Glance), and uniquely identify a CERN author. However, for the time being, we decided to rely on ORCiD, when available. The major limitation to this is that other systems might not rely on the ORCiD dump: they most probably get the users from the CERN users database, and only a small percentage of users added their ORCiD to their CERN account.
We will tackle this in the future, if needed.

Practically, all this means avoiding adding the Person ID in the `identifiers` field in the names vocabulary. However, the Person ID is still needed in the names vocabulary to be able to sync the CERN users db with it.

## Changes

1. We will not have the Person ID in the record (creator+contributors fields)
2. We will add a new db table column `institutional_id/internal_id/user_id` to the names table, where we can store the CERN Person ID, and we will make sure that it will not be copied over to the record.
3. For the time being, this new `internal_id` will not be added to the names vocabulary, as it is not needed. If needed in the future, we will have to apply field permissions to this field, to restrict who can see it.
4. Other external systems will have to rely on ORCiD for data exchange.

## Tasks
- [x] add `internal_id` to names db table
- [x] remove person id from identifiers
- [ ] fix sync script to match by internal id
- [ ] fix the scheme in the deposit form
- [x] fix migration not to store person id on the identifiers list, but in the institutional id db col
- [ ] document the decisions in the log
- [ ] documentation for RDM of the new db col and use cases (syncing with institutional users db)
